version: '3.8'

services:
  postgres-master:
    image: postgres:15
    container_name: postgres-master
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_master_data:/var/lib/postgresql/data
      - ./master-config:/etc/postgresql
      - ./scripts/master-init.sh:/docker-entrypoint-initdb.d/01-master-init.sh
    networks:
      - postgres-network
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf

  postgres-standby:
    image: postgres:15
    container_name: postgres-standby
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5433:5432"
    volumes:
      - postgres_standby_data:/var/lib/postgresql/data
      - ./standby-config:/etc/postgresql
      - ./scripts/standby-init.sh:/docker-entrypoint-initdb.d/01-standby-init.sh
    networks:
      - postgres-network
    depends_on:
      - postgres-master
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf

volumes:
  postgres_master_data:
  postgres_standby_data:

networks:
  postgres-network:
    driver: bridge